# Generated by Django 5.0.3 on 2024-03-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='good_student',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='locker_combination',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='locker_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='personal_email',
            field=models.CharField(default='None', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='student_email',
            field=models.CharField(default='None', max_length=100),
            preserve_default=False,
        ),
    ]
